workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 60
    environment:
      node: 18
      java: 17
    scripts:
      - name: List directory structure
        script: |
          ls -la
          find . -name "gradlew" -type f
      - name: Install dependencies
        script: |
          if [ -d "mobile" ]; then
            cd mobile
            npm install
          else
            npm install
          fi
      - name: Build APK
        script: |
          cd mobile
          npm install
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug || echo "Gradle build failed, but continuing..."
          find . -name "*.apk" -type f
    artifacts:
      - "**/build/outputs/**/*.apk"