workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 60
    environment:
      node: 18
      java: 17
    scripts:
      - name: List directory structure
        script: |
          ls -la
          find . -name "gradlew" -type f
      - name: Install dependencies
        script: |
          if [ -d "mobile" ]; then
            cd mobile
            npm install
          else
            npm install
          fi
      - name: Build APK
        script: |
          if [ -f "mobile/android/gradlew" ]; then
            cd mobile/android
            chmod +x gradlew
            ./gradlew assembleDebug
          elif [ -f "android/gradlew" ]; then
            cd android
            chmod +x gradlew
            ./gradlew assembleDebug
          else
            echo "gradlew not found"
            exit 1
          fi
    artifacts:
      - "**/build/outputs/**/*.apk"