workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m1
    working_directory: mobile
    environment:
      vars:
        PACKAGE_NAME: "com.silentzoneapp"
      node: 18
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Generate keystore
        script: |
          cd android/app
          keytool -genkeypair -v -storetype PKCS12 -keystore my-upload-key.keystore -alias my-key-alias -keyalg RSA -keysize 2048 -validity 10000 -storepass silentzone -keypass silentzone -dname "CN=Silent Zone"
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
      - name: Build Android release
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - mobile/android/app/build/outputs/**/*.apk
      - mobile/android/app/build/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: false