workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      node: 18
    scripts:
      - name: Install dependencies
        script: |
          cd mobile
          npm install
      - name: Build Android APK
        script: |
          cd mobile
          npx react-native build-android --mode=debug
    artifacts:
      - mobile/android/app/build/outputs/**/*.apk